### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by SabLeCam** [andersgs/irelr#1]
Hi anders, 
I've been trying to install the irelr package, following your guidelines.
I'm working with the latest version of R and DevTools.
I get this error message "Error: Could not find build tools necessary to build irelr" and then RTools start being installed on my computer.
I've installed independantly the latest version of RTools (3.4) but that didn't solve the problem.
Any idea on the cause of this error?
In advance thanks
Sabrina

**Comment by andersgs** [comment]
Hi Sabrina.

Are you trying to install on a Windows machine? I have never tried it myself, so am not sure it would be successful. I'll see what I can do.

Anders.

**Comment by andersgs** [comment]
Hi Sabrina.

Apologies for the delay. I have added a Windows binary, and added instructions on the README.md file on how to install it. I have run a cursory test, and it seems to work. I am curious to hear how you go.

Best.

Anders.
