### ISSUE TITLE
Installation issue 2

### ISSUE THREAD

**Issue by vlkofly** [andersgs/irelr#2]
The installation failed because of error in vignette creation, it misses some aesthetics xintercept in the script use-irelr.Rmd. 

OS Ubuntu 16.04
R version 3.3.2 (2016-10-31)

Installation output:
> install_github("andersgs/irelr", build_vignettes = TRUE)
Downloading GitHub repo andersgs/irelr@master
from URL https://api.github.com/repos/andersgs/irelr/zipball/master
Installing irelr
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD build  \
  '/tmp/Rtmpytl4Jy/devtools182f7946dc1b/andersgs-irelr-5ee727e' --no-resave-data --no-manual 

* checking for file ‘/tmp/Rtmpytl4Jy/devtools182f7946dc1b/andersgs-irelr-5ee727e/DESCRIPTION’ ... OK
* preparing ‘irelr’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to build vignettes
* creating vignettes ... ERROR
Loading required package: adegenet
Loading required package: ade4

   /// adegenet 2.0.1 is loaded ////////////

   > overview: '?adegenet'
   > tutorials/doc/questions: 'adegenetWeb()' 
   > bug reports/feature requests: adegenetIssues()

Loading required package: irelr
Welcome to irelr (version 0.0.4)

Attaching package: 'irelr'

The following object is masked from 'package:adegenet':

    read.genepop

Loading required package: data.table
Loading required package: moments
Loading required package: reshape2

Attaching package: 'reshape2'

The following objects are masked from 'package:data.table':

    dcast, melt

Loading required package: ggplot2
Loading required package: gridExtra
`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
Quitting from lines 380-390 (use-irelr.Rmd) 
Error: processing vignette 'use-irelr.Rmd' failed with diagnostics:
geom_vline requires the following missing aesthetics: xintercept
Execution halted
Error: Command failed (1)
___________________________________________________________________

**Comment by vlkofly** [comment]
The issue is caused by a syntax change in ggplot2_2.2.0
**geom_vline(x=**...) needs to be replaced by **geom_vline(xintercept=**...)
and
**geom_hline(y=**...) by **geom_hline(yintercept=**...)

in the use-irelr.Rmd script

I was able to install this package from local downloaded and fixed source code.

**Comment by andersgs** [comment]
Hi I am looking into it. Thank you for posting the issue.

**Comment by andersgs** [comment]
This is fixed in the new version `0.0.6` .
